### ISSUE TITLE
I'm getting error when in the middle of install.

### ISSUE THREAD

**Issue by KintCark** [Woolverine94/biniou#39] opened 2024-08-28 01:45 UTC
× Getting requirements to build wheel did not run successfully.                                             │ exit code: 1
  ╰─> [2 lines of output]                                   [Errno 2] No such file or directory: 'pkg-config'
      ERROR: No SWIG source for libexiv2 version None       [end of output]

Is there a way to fix this error?

Update: chat gpt fixed my error but I ran Into so many issues its impossible to install on aarch64 linux. Images try the windows install on winlator im trying to Install this on android termux

**Comment by Woolverine94** [comment] 2024-08-28 16:39
Hello @KintCark,

Thanks for your report and your interest in the project.

Your error message seems to be linked to a missing libexiv2 library which is required for handling of metadatas in the images output.

Also, I can confirm you that biniou is not compatible with aarch64. 
Amd64 is the only CPU architecture currently supported. 
Last time I tried on a Raspberry Pi 5, some modules and dependencies don't support/compile for aarch64, so there's no workaround or anything that can be done a this time.  Only working part was the chatbot.

I close this issue as there is nothing that can be done.

**Closed by Woolverine94** 2024-08-28 16:39 UTC
Labels: wontfix

**Comment by KintCark** [comment] 2024-08-28 17:52
Yea is I found out with chat gpt hopefully you will add aarch64 linux support in the future

**Comment by Woolverine94** [comment] 2024-08-28 18:47
I would really like to support devices like Raspberry Pi 5, but at this time this doesn't seems possible.

Wait & see ! ;)
