### ISSUE TITLE
Empty settings tabs

### ISSUE THREAD

**Issue by aolko** [Woolverine94/biniou#23] opened 2024-06-15 14:21 UTC
**Describe the bug**
Every tab except the first in settings is empty

**To Reproduce**
1. Go to 'Global settings'
2. Click on tabs
3. See error

**Expected behavior**
Non-empty tabs with related settings

**Console log**
```
>>>[biniou 🧠]: Up and running at https://192.168.1.72:7860/?__theme=dark
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
Running on local URL:  https://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
>>>[Kandinsky 🖼️ ]: starting module
>>>[GFPGAN-mini 🔎]: enhanced 1 image
>>>[Kandinsky 🖼️ ]: generated 1 batch(es) of 1
>>>[Kandinsky 🖼️ ]: Settings : Model=kandinsky-community/kandinsky-2-2-decoder | Sampler=Euler | Steps=25 | CFG scale=4 | Size=512x512 | GFPGAN=True | Prompt=a cute kitten | Negative prompt=
>>>[Kandinsky 🖼️ ]: leaving module
>>>[biniou 🧠]: Generation finished in 00:06:49 (409 seconds)
>>>[Kandinsky 🖼️ ]: starting module
```
```
E:\ai\Biniou\biniou>REM ***********************

E:\ai\Biniou\biniou>REM *** BINIOU LAUNCHER ***

E:\ai\Biniou\biniou>REM ***********************

E:\ai\Biniou\biniou>call venv.cmd

E:\ai\Biniou\biniou>.\env\Scripts\activate
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
>>>[biniou 🧠]: Up and running at https://192.168.1.72:7860/?__theme=dark
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
--------
Running on local URL:  https://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
>>>[Kandinsky 🖼️ ]: starting module
>>>[GFPGAN-mini 🔎]: enhanced 1 image
>>>[Kandinsky 🖼️ ]: generated 1 batch(es) of 1
>>>[Kandinsky 🖼️ ]: Settings : Model=kandinsky-community/kandinsky-2-2-decoder | Sampler=Euler | Steps=25 | CFG scale=4 | Size=512x512 | GFPGAN=True | Prompt=a cute kitten | Negative prompt=
>>>[Kandinsky 🖼️ ]: leaving module
>>>[biniou 🧠]: Generation finished in 00:06:49 (409 seconds)
>>>[Kandinsky 🖼️ ]: starting module
```

**Screenshots**
![image](https://github.com/Woolverine94/biniou/assets/581458/4dbe9b96-29c4-4d8e-af71-2da945de0c0e)

**Hardware (please complete the following information):**
 - RAM size: 32GB
 - Processor physical core number or vcore number : 6
 - Storage type of biniou installation : HDD
 - Free storage space for biniou installation : 294GB free, 25GB deployed
 - GPU : NVIDIA GeForce GTX 1060 6GB

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 
 - Browser chrome (thorium)
 - Version 124.0.6367.218
 - Python version 3.11.6

**Smartphone (please complete the following information):**
 - N/A

**Additional informations**
 - I access the webui through the ip 127.0.0.1 (browser and biniou installation on the same system) :
[X] Yes [ ] No

**Additional context**

**Comment by Woolverine94** [comment] 2024-06-15 14:52
Hello @aolko,

This is an expected behavior : since commit f9738c3, setting panel is secured by a login system.  

You have to login using the "Global settings login" tab (selected by default when you click on "Global settings" tab).

Default credentials are user = biniou / password = biniou and can be changed by editing the first line of the file `.ini/auth.cfg` in the biniou root directory. 

This file is also used as credentials for the "online" authentication provided by gradio.

I close this issue as I consider this is not a real bug, but more a lack of documentation on my side, please do not hesitate to re-open it if required.

**Closed by Woolverine94** 2024-06-15 14:52 UTC
Labels: documentation
