### ISSUE TITLE
can't start app using docker

### ISSUE THREAD

**Issue by dhlsam** [Woolverine94/biniou#11] opened 2024-01-30 18:06 UTC
There was a problem when trying to write in your cache folder (/home/biniou/.cache/huggingface/hub). Please, ensure the directory exists and can be written to.
There was a problem when trying to write in your cache folder (/home/biniou/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
Traceback (most recent call last):
  File "/home/biniou/biniou/webui.py", line 14, in <module>
    from ressources import *
  File "/home/biniou/biniou/ressources/__init__.py", line 2, in <module>
    from .llamacpp import *
  File "/home/biniou/biniou/ressources/llamacpp.py", line 11, in <module>
    os.makedirs(model_path_llamacpp, exist_ok=True)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: './models/llamacpp/'

<img width="1091" alt="2024-01-31 02 13 03" src="https://github.com/Woolverine94/biniou/assets/390439/5372dcf7-2503-496a-a9c0-44c9ded85c77">

**Comment by Woolverine94** [comment] 2024-01-30 19:05
Hello @dhlsam,

Thanks for your feedback. 

Can you give more context on your installation ? 

Can you confirm that you launch biniou using :

```bash
docker run -it --restart=always -p 7860:7860 \
-v biniou_outputs:/home/biniou/biniou/outputs \
-v biniou_models:/home/biniou/biniou/models \
-v biniou_cache:/home/biniou/.cache/huggingface \
-v biniou_gfpgan:/home/biniou/biniou/gfpgan \
biniou:latest
```
As it seems that you don't have writing permissions on at least `models` and `.cache` folders, can you also post the result of : 
```bash
ls -Al /mnt/user/ssd/biniou/
```

**Comment by Woolverine94** [comment] 2024-01-30 21:38
For further information @dhlsam ,

Definitely a permission issue on your side : 

  * Can't reproduce with standard installation
  * Can reproduce (same error message) with changing defaults volume root to /mnt/user/ssd/biniou 

I've solved it by giving ownership of /mnt/user/ssd/biniou to the standard user I use to execute the docker command : 
```bash
chown -R <username>:root /mnt/user/ssd/biniou
```
If it's not applicable in your environment, please consider using setfacl to add write rights to the biniou directory and its subfolder. 

I close the issue, please don't hesitate to re-open if needed.

**Closed by Woolverine94** 2024-01-30 21:38 UTC
