### ISSUE TITLE
.exe fail instalation in windows 10

### ISSUE THREAD

**Issue by sontoriyama** [Woolverine94/biniou#38] opened 2024-08-27 15:31 UTC
one windows say "finishing instalation..." never finish. and other windows (terminal ms2) say:

C:\Windows\system32>REM **************************************************

C:\Windows\system32>REM *** DOWNLOADING AND INSTALLING PREREQUISITES : ***

C:\Windows\system32>REM **************************************************

C:\Windows\system32>set URL_GIT="https://github.com/git-for-windows/git/releases/download/v2.45.2.windows.1/Git-2.45.2-64-bit.exe"

C:\Windows\system32>set URL_OPENSSL="https://download.firedaemon.com/FireDaemon-OpenSSL/FireDaemon-OpenSSL-x64-3.3.1.exe"

C:\Windows\system32>set URL_PYTHON="https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe"

C:\Windows\system32>set URL_VSBT="https://aka.ms/vs/17/release/vs_BuildTools.exe"

C:\Windows\system32>set URL_FFMPEG="https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"

C:\Windows\system32>set URL_VCREDIST="https://aka.ms/vs/17/release/vc_redist.x64.exe"

C:\Windows\system32>set WIN10_SDK="Microsoft.VisualStudio.Component.Windows10SDK.20348"

C:\Windows\system32>set WIN11_SDK="Microsoft.VisualStudio.Component.Windows11SDK.22621"

C:\Windows\system32>curl -o "C:\Users\goku\AppData\Local\Temp\wget.exe" "https://eternallybored.org/misc/wget/1.21.4/64/wget.exe"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6880k  100 6880k    0     0  7889k      0 --:--:-- --:--:-- --:--:-- 7927k

C:\Windows\system32>C:\Users\goku\AppData\Local\Temp\wget -O "C:\Users\goku\AppData\Local\Temp\vs_BuildTools.exe" "https://aka.ms/vs/17/release/vs_BuildTools.exe"
--2024-08-27 15:47:30--  https://aka.ms/vs/17/release/vs_BuildTools.exe
Resolving aka.ms (aka.ms)... 23.32.85.135
Connecting to aka.ms (aka.ms)|23.32.85.135|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.visualstudio.microsoft.com/download/pr/db4c3f2d-694d-406b-8fb6-1924f3fc3580/02f7788cb00c9e0aa87ce0c1e923f7b12921aa1f06d9f78261ee0e3e5c794332/vs_BuildTools.exe [following]
--2024-08-27 15:47:31--  https://download.visualstudio.microsoft.com/download/pr/db4c3f2d-694d-406b-8fb6-1924f3fc3580/02f7788cb00c9e0aa87ce0c1e923f7b12921aa1f06d9f78261ee0e3e5c794332/vs_BuildTools.exe
Resolving download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)... 68.232.34.200
Connecting to download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)|68.232.34.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4421088 (4,2M) [application/octet-stream]
Saving to: 'C:/Users/goku/AppData/Local/Temp/vs_BuildTools.exe'

C:/Users/goku/AppData/Local/T 100%[=================================================>]   4,22M  --.-KB/s    in 0,07s

2024-08-27 15:47:31 (58,1 MB/s) - 'C:/Users/goku/AppData/Local/Temp/vs_BuildTools.exe' saved [4421088/4421088]

C:\Windows\system32>C:\Users\goku\AppData\Local\Temp\wget -O "C:\Users\goku\AppData\Local\Temp\git.exe" "https://github.com/git-for-windows/git/releases/download/v2.45.2.windows.1/Git-2.45.2-64-bit.exe"
--2024-08-27 15:47:31--  https://github.com/git-for-windows/git/releases/download/v2.45.2.windows.1/Git-2.45.2-64-bit.exe
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/23216272/5027ef70-01f5-49c4-8237-a5ce3455e7d6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240827%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240827T134731Z&X-Amz-Expires=300&X-Amz-Signature=46a64510e055dfb53311d63a7621cb7203f038cd2896bf68061df78aba0fcb8f&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=23216272&response-content-disposition=attachment%3B%20filename%3DGit-2.45.2-64-bit.exe&response-content-type=application%2Foctet-stream [following]
--2024-08-27 15:47:31--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/23216272/5027ef70-01f5-49c4-8237-a5ce3455e7d6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240827%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240827T134731Z&X-Amz-Expires=300&X-Amz-Signature=46a64510e055dfb53311d63a7621cb7203f038cd2896bf68061df78aba0fcb8f&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=23216272&response-content-disposition=attachment%3B%20filename%3DGit-2.45.2-64-bit.exe&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 68131584 (65M) [application/octet-stream]
Saving to: 'C:/Users/goku/AppData/Local/Temp/git.exe'

C:/Users/goku/AppData/Local/T 100%[=================================================>]  64,97M  69,8MB/s    in 0,9s

2024-08-27 15:47:33 (69,8 MB/s) - 'C:/Users/goku/AppData/Local/Temp/git.exe' saved [68131584/68131584]

C:\Windows\system32>C:\Users\goku\AppData\Local\Temp\wget -O "C:\Users\goku\AppData\Local\Temp\openssl.exe" "https://download.firedaemon.com/FireDaemon-OpenSSL/FireDaemon-OpenSSL-x64-3.3.1.exe" --no-check-certificate
--2024-08-27 15:47:33--  https://download.firedaemon.com/FireDaemon-OpenSSL/FireDaemon-OpenSSL-x64-3.3.1.exe
Resolving download.firedaemon.com (download.firedaemon.com)... 172.67.74.131, 104.26.10.34, 104.26.11.34
Connecting to download.firedaemon.com (download.firedaemon.com)|172.67.74.131|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13122808 (13M) [application/x-msdownload]
Saving to: 'C:/Users/goku/AppData/Local/Temp/openssl.exe'

C:/Users/goku/AppData/Local/T 100%[=================================================>]  12,51M  65,9MB/s    in 0,2s

2024-08-27 15:47:34 (65,9 MB/s) - 'C:/Users/goku/AppData/Local/Temp/openssl.exe' saved [13122808/13122808]

C:\Windows\system32>C:\Users\goku\AppData\Local\Temp\wget -O "C:\Users\goku\AppData\Local\Temp\python.exe" "https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe" --no-check-certificate
--2024-08-27 15:47:34--  https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe
Resolving www.python.org (www.python.org)... 151.101.132.223
Connecting to www.python.org (www.python.org)|151.101.132.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26216840 (25M) [application/octet-stream]
Saving to: 'C:/Users/goku/AppData/Local/Temp/python.exe'

C:/Users/goku/AppData/Local/T 100%[=================================================>]  25,00M  68,0MB/s    in 0,4s

2024-08-27 15:47:35 (68,0 MB/s) - 'C:/Users/goku/AppData/Local/Temp/python.exe' saved [26216840/26216840]

C:\Windows\system32>C:\Users\goku\AppData\Local\Temp\wget -O "C:\Users\goku\AppData\Local\Temp\ffmpeg-master-latest-win64-gpl.zip" "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"
--2024-08-27 15:47:35--  https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/292087234/f29f948c-bc24-456f-b457-31525888a350?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240827%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240827T134735Z&X-Amz-Expires=300&X-Amz-Signature=d6124a35307ac74b3c0e0b555d7155ed1978cd6cbad9395421cee5b2b1b0b73a&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=292087234&response-content-disposition=attachment%3B%20filename%3Dffmpeg-master-latest-win64-gpl.zip&response-content-type=application%2Foctet-stream [following]
--2024-08-27 15:47:35--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/292087234/f29f948c-bc24-456f-b457-31525888a350?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240827%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240827T134735Z&X-Amz-Expires=300&X-Amz-Signature=d6124a35307ac74b3c0e0b555d7155ed1978cd6cbad9395421cee5b2b1b0b73a&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=292087234&response-content-disposition=attachment%3B%20filename%3Dffmpeg-master-latest-win64-gpl.zip&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 149841958 (143M) [application/octet-stream]
Saving to: 'C:/Users/goku/AppData/Local/Temp/ffmpeg-master-latest-win64-gpl.zip'

C:/Users/goku/AppData/Local/T 100%[=================================================>] 142,90M  30,9MB/s    in 4,6s

2024-08-27 15:47:40 (31,0 MB/s) - 'C:/Users/goku/AppData/Local/Temp/ffmpeg-master-latest-win64-gpl.zip' saved [149841958/149841958]

C:\Windows\system32>C:\Users\goku\AppData\Local\Temp\wget -O "C:\Users\goku\AppData\Local\Temp\vcredist.exe" "https://aka.ms/vs/17/release/vc_redist.x64.exe"
--2024-08-27 15:47:40--  https://aka.ms/vs/17/release/vc_redist.x64.exe
Resolving aka.ms (aka.ms)... 23.60.102.83
Connecting to aka.ms (aka.ms)|23.60.102.83|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.visualstudio.microsoft.com/download/pr/1754ea58-11a6-44ab-a262-696e194ce543/3642E3F95D50CC193E4B5A0B0FFBF7FE2C08801517758B4C8AEB7105A091208A/VC_redist.x64.exe [following]
--2024-08-27 15:47:41--  https://download.visualstudio.microsoft.com/download/pr/1754ea58-11a6-44ab-a262-696e194ce543/3642E3F95D50CC193E4B5A0B0FFBF7FE2C08801517758B4C8AEB7105A091208A/VC_redist.x64.exe
Resolving download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)... 68.232.34.200
Connecting to download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)|68.232.34.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25397512 (24M) [application/octet-stream]
Saving to: 'C:/Users/goku/AppData/Local/Temp/vcredist.exe'

C:/Users/goku/AppData/Local/T 100%[=================================================>]  24,22M  48,9MB/s    in 0,5s

2024-08-27 15:47:42 (48,9 MB/s) - 'C:/Users/goku/AppData/Local/Temp/vcredist.exe' saved [25397512/25397512]

C:\Windows\system32>start /wait C:\Users\goku\AppData\Local\Temp\vs_BuildTools.exe --add "Microsoft.VisualStudio.Component.Windows10SDK.20348" --add "Microsoft.VisualStudio.Component.Windows11SDK.22621" --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --passive --wait

C:\Windows\system32>start /wait C:\Users\goku\AppData\Local\Temp\git.exe /silent

C:\Windows\system32>start /wait C:\Users\goku\AppData\Local\Temp\openssl.exe /passive

C:\Windows\system32>start /wait C:\Users\goku\AppData\Local\Temp\python.exe /passive

C:\Windows\system32>start /wait C:\Users\goku\AppData\Local\Temp\vcredist.exe  /q /norestart

C:\Windows\system32>start /wait powershell -command "Expand-Archive C:\Users\goku\AppData\Local\Temp\ffmpeg-master-latest-win64-gpl.zip C:\Users\goku\AppData\Local\Programs\ffmpeg -Force"

C:\Windows\system32>REM ****************************

C:\Windows\system32>REM *** CLONING REPOSITORY : ***

C:\Windows\system32>REM ****************************

C:\Windows\system32>cd "C:\Users\goku"

C:\Users\goku>set path=C:\Program Files\Lapce\;C:\programes\ImageMagick-7.1.1-Q8;C:\programes\ImageMagick-7.1.1-Q16-HDRI;C:\Program Files\Alacritty\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\libnvvp;;C:\programes\Python312\Scripts\;C:\programes\Python312\;C:\programes\Python311\Scripts\;C:\programes\Python311\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Windows Kits\10\Microsoft Application Virtualization\Sequencer\;C:\programes\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\NVIDIA Corporation\Nsight Compute 2024.2.0\;C:\Program Files\RedHat\Podman\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\lib\mpv.install\tools;C:\Program Files\dotnet\;C:\programes\PuTTY\;C:\programes\Sniffnet\;C:\Program Files\Cloudflare\Cloudflare WARP\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Docker\Docker\resources\bin;C:\Users\goku\.cargo\bin;C:\Users\goku\AppData\Local\pnpm;C:\Users\goku\AppData\Local\Microsoft\WindowsApps;C:\programes\VScode\bin;C:\Users\goku\AppData\Local\Programs\Ollama;C:\Users\goku\AppData\Local\Microsoft\WinGet\Links;C:\Users\goku\.bun\bin;C:\Users\goku\.deno\bin;C:\Users\goku\AppData\Roaming\npm;C:\Users\goku\.dotnet\tools;C:\Program Files\Git\cmd;

C:\Users\goku>git clone --branch main https://github.com/Woolverine94/biniou.git
Cloning into 'biniou'...
remote: Enumerating objects: 3778, done.
remote: Counting objects: 100% (811/811), done.
remote: Compressing objects: 100% (197/197), done.
remote: Total 3778 (delta 622), reused 798 (delta 614), pack-reused 2967 (from 1)
Receiving objects: 100% (3778/3778), 5.05 MiB | 10.10 MiB/s, done.
Resolving deltas: 100% (2823/2823), done.

C:\Users\goku>git config --global --add safe.directory "C:/Users/goku/biniou"

C:\Users\goku>cd "C:\Users\goku\biniou"

C:\Users\goku\biniou>REM ******************************

C:\Users\goku\biniou>REM *** CREATING DIRECTORIES : ***

C:\Users\goku\biniou>REM ******************************

C:\Users\goku\biniou>mkdir "C:\Users\goku\biniou\outputs"

C:\Users\goku\biniou>mkdir "C:\Users\goku\biniou\ssl"

C:\Users\goku\biniou>mkdir "C:\Users\goku\biniou\models\Audiocraft"

C:\Users\goku\biniou>REM ***********************************************

C:\Users\goku\biniou>REM *** INSTALLING PYTHON VIRTUAL ENVIRONMENT : ***

C:\Users\goku\biniou>REM ***********************************************

C:\Users\goku\biniou>"C:\Program Files\FireDaemon OpenSSL 3\bin\openssl.exe" req -x509 -newkey rsa:4096 -keyout "C:\Users\goku\biniou\ssl\key.pem" -out "C:\Users\goku\biniou\ssl\cert.pem" -sha256 -days 3650 -nodes -subj "/C=FR/ST=Paris/L=Paris/O=Biniou/OU=/CN="
.....+++++++++++++++++++++++++++++++++++++++++++++*......+......+.+.....+....+++++++++++++++++++++++++++++++++++++++++++++*.......+........+.+..+....+........+................+..............+.................................+.......+.....+.+...........+.............+.................+.........+++++
...+.............+.....+.+.....+....+..+...+.......+..............+.+...+.....+....+++++++++++++++++++++++++++++++++++++++++++++*...+....+.....+...+..........+...+..+...+...+.+.....+.+.........+.........+.....+....+...+..+......+....+...+...+.....+......+......+....+.....+...+.+.........+............+...+......+.....+++++++++++++++++++++++++++++++++++++++++++++*.....+..........+..................+..+.............+........+............+...+............+...+...+......+...............+......+...............+...+..........+...............+..+.......+........+....+...........+...+......+...+.+.....+.+......+...+.....+.........+...+.........+.....................+.......+............+...+.....+..........+...+..+............+....+.........+...........+.......+............+..+...+.......+...+...........+.+........+...+....+...+......+...............+..+.......+..........................+..........+.........+.....+......+....+...........+......+.+........+.......+...............+........+.......+...............+.........+.........+.....+++++
-----
req warning: No value provided for subject name attribute "OU", skipped
req warning: No value provided for subject name attribute "CN", skipped

C:\Users\goku\biniou>"C:\Users\goku\AppData\Local\Programs\Python\Python311\python.exe" -m pip install --upgrade pip
El sistema no puede encontrar la ruta especificada.

C:\Users\goku\biniou>"C:\Users\goku\AppData\Local\Programs\Python\Python311\Scripts\pip" install virtualenv
El sistema no puede encontrar la ruta especificada.

C:\Users\goku\biniou>"C:\Users\goku\AppData\Local\Programs\Python\Python311\python.exe" -m venv env
El sistema no puede encontrar la ruta especificada.

C:\Users\goku\biniou>call venv.cmd

C:\Users\goku\biniou>.\env\Scripts\activate
El sistema no puede encontrar la ruta especificada.

C:\Users\goku\biniou>python.exe -m pip install --upgrade pip
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: pip in c:\programes\python312\lib\site-packages (24.2)

C:\Users\goku\biniou>pip install wheel
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting wheel
  Downloading wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
Downloading wheel-0.44.0-py3-none-any.whl (67 kB)
Installing collected packages: wheel
Successfully installed wheel-0.44.0

C:\Users\goku\biniou>pip install torch==2.1.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
Looking in indexes: https://download.pytorch.org/whl/cpu, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement torch==2.1.0 (from versions: 2.2.0+cpu, 2.2.1+cpu, 2.2.2+cpu, 2.3.0+cpu, 2.3.1+cpu, 2.4.0+cpu)
ERROR: No matching distribution found for torch==2.1.0

C:\Users\goku\biniou>pip install llama-cpp-python
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting llama-cpp-python
  Downloading llama_cpp_python-0.2.89.tar.gz (64.3 MB)
     ---------------------------------------- 64.3/64.3 MB 75.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=4.5.0 in c:\programes\python312\lib\site-packages (from llama-cpp-python) (4.12.2)
Requirement already satisfied: numpy>=1.20.0 in c:\programes\python312\lib\site-packages (from llama-cpp-python) (1.26.4)
Requirement already satisfied: diskcache>=5.6.1 in c:\programes\python312\lib\site-packages (from llama-cpp-python) (5.6.3)
Requirement already satisfied: jinja2>=2.11.3 in c:\programes\python312\lib\site-packages (from llama-cpp-python) (3.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programes\python312\lib\site-packages (from jinja2>=2.11.3->llama-cpp-python) (2.1.5)
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... done
  Created wheel for llama-cpp-python: filename=llama_cpp_python-0.2.89-cp312-cp312-win_amd64.whl size=3120140 sha256=2bdca93732a6dd6cc1850e5ec536dc3ee109c90cdc48799f2604267fe8fbe210
  Stored in directory: C:\Users\goku\AppData\Local\Temp\pip-ephem-wheel-cache-pm3rz_2m\wheels\b7\28\d0\70cbdbd996639a4e7cd9afb185e84ff5db750ac26c85ac94ff
Successfully built llama-cpp-python
Installing collected packages: llama-cpp-python
Successfully installed llama-cpp-python-0.2.89

C:\Users\goku\biniou>pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting git+https://github.com/facebookresearch/audiocraft (from -r requirements.txt (line 14))
  Cloning https://github.com/facebookresearch/audiocraft to c:\users\goku\appdata\local\temp\pip-req-build-mxtiop2f
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/audiocraft 'C:\Users\goku\AppData\Local\Temp\pip-req-build-mxtiop2f'
  Resolved https://github.com/facebookresearch/audiocraft to commit adf0b04a4452f171970028fcf80f101dd5e26e19
  Preparing metadata (setup.py) ... done
Collecting git+https://github.com/ai-forever/Real-ESRGAN.git (from -r requirements.txt (line 15))
  Cloning https://github.com/ai-forever/Real-ESRGAN.git to c:\users\goku\appdata\local\temp\pip-req-build-_fmcax1u
  Running command git clone --filter=blob:none --quiet https://github.com/ai-forever/Real-ESRGAN.git 'C:\Users\goku\AppData\Local\Temp\pip-req-build-_fmcax1u'
  Resolved https://github.com/ai-forever/Real-ESRGAN.git to commit 362a0316878f41dbdfbb23657b450c3353de5acf
  Preparing metadata (setup.py) ... done
Collecting git+https://github.com/TencentARC/PhotoMaker.git@ec35a8716ea790a404cb7e1ba282a320454906d1 (from -r requirements.txt (line 24))
  Cloning https://github.com/TencentARC/PhotoMaker.git (to revision ec35a8716ea790a404cb7e1ba282a320454906d1) to c:\users\goku\appdata\local\temp\pip-req-build-u8siy47q
  Running command git clone --filter=blob:none --quiet https://github.com/TencentARC/PhotoMaker.git 'C:\Users\goku\AppData\Local\Temp\pip-req-build-u8siy47q'
  Running command git rev-parse -q --verify 'sha^ec35a8716ea790a404cb7e1ba282a320454906d1'
  Running command git fetch -q https://github.com/TencentARC/PhotoMaker.git ec35a8716ea790a404cb7e1ba282a320454906d1
  Running command git checkout -q ec35a8716ea790a404cb7e1ba282a320454906d1
  Resolved https://github.com/TencentARC/PhotoMaker.git to commit ec35a8716ea790a404cb7e1ba282a320454906d1
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gradio==3.50.2 (from -r requirements.txt (line 1))
  Downloading gradio-3.50.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: transformers in c:\programes\python312\lib\site-packages (from -r requirements.txt (line 2)) (4.43.3)
Collecting sentencepiece (from -r requirements.txt (line 3))
  Downloading sentencepiece-0.2.0-cp312-cp312-win_amd64.whl.metadata (8.3 kB)
Collecting accelerate (from -r requirements.txt (line 4))
  Downloading accelerate-0.33.0-py3-none-any.whl.metadata (18 kB)
Collecting diffusers==0.30.0 (from -r requirements.txt (line 5))
  Downloading diffusers-0.30.0-py3-none-any.whl.metadata (18 kB)
Collecting compel (from -r requirements.txt (line 6))
  Downloading compel-2.0.3-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: scipy in c:\programes\python312\lib\site-packages (from -r requirements.txt (line 7)) (1.13.1)
Collecting opencv-python (from -r requirements.txt (line 8))
  Downloading opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting imageio (from -r requirements.txt (line 9))
  Downloading imageio-2.35.1-py3-none-any.whl.metadata (4.9 kB)
Collecting imageio-ffmpeg (from -r requirements.txt (line 10))
  Downloading imageio_ffmpeg-0.5.1-py3-none-win_amd64.whl.metadata (1.6 kB)
Collecting numpy==1.25.2 (from -r requirements.txt (line 11))
  Downloading numpy-1.25.2.tar.gz (10.8 MB)
     ---------------------------------------- 10.8/10.8 MB 67.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\programes\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\programes\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\programes\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\programes\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\programes\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\goku\AppData\Local\Temp\pip-build-env-fyrh037t\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\goku\AppData\Local\Temp\pip-build-env-fyrh037t\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\goku\AppData\Local\Temp\pip-build-env-fyrh037t\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\Users\goku\biniou>echo "Installation finished ! You could now launch biniou by double-clicking C:\Users\goku\biniou\webui.cmd"
"Installation finished ! You could now launch biniou by double-clicking C:\Users\goku\biniou\webui.cmd"

C:\Users\goku\biniou>pause
Presione una tecla para continuar . . .

but you press enter etc and not work

thanks!

**Comment by c0ffincolors** [comment] 2024-08-27 16:05
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Woolverine94** [comment] 2024-08-27 16:28
Hello @sontoriyama,

Thanks for your report and your interest in the project.

Your problem is -at least- that python 3.11 is not found at the expected path, and is required for biniou's installation (it seems that python 3.12 is also installed on your system and isn't compatible with biniou currently) : 

> C:\Users\goku\biniou>"C:\Users\goku\AppData\Local\Programs\Python\Python311\python.exe" -m pip install --upgrade pip
El sistema no puede encontrar la ruta especificada.
C:\Users\goku\biniou>"C:\Users\goku\AppData\Local\Programs\Python\Python311\Scripts\pip" install virtualenv
El sistema no puede encontrar la ruta especificada.
C:\Users\goku\biniou>"C:\Users\goku\AppData\Local\Programs\Python\Python311\python.exe" -m venv env
El sistema no puede encontrar la ruta especificada.

Only workaround I can recommend at this time is using a virtual machine with either a fresh windows/linux installation or the provided Dockerfile (either CPU or CUDA) if you have this opportunity.

**Comment by Woolverine94** [comment] 2024-08-29 19:57
Hello @sontoriyama,

After further investigations, I can't reproduce the problem. 

It's definitely linked to the missing Python 3.11, which could have the following causes : 
  - For some reasons, python installer was corrupted during download and the "/passive" argument passed at install time hides an error message
  - You didn't run the installer with administrator privileges (which is perfectly understandable) and you didn't validate an unlikely UAC for the python installer (Windows sometimes minimize it in the task bar, and you only have 2 minutes to validate it before it timeout) 

The Python 3.12 installation should not be a problem, as I can perfectly deploy biniou in a Windows environment already using Python 3.12.

I can only advise you to delete the existing biniou directory and relaunch the installer with administrator privileges.
You can also launch without admin rights, but you should then monitor the pre-requisites installation and watch for the UAC pop-ups. 

I close this issue as it really looks like a problem on your side, but don't hesitate to re-open it if required.

**Comment by Woolverine94** [comment] 2024-08-29 19:58
Hello @sontoriyama,

After further investigations, I can't reproduce the problem. 

It's definitely linked to the missing Python 3.11, which could have the following causes : 
  - For some reasons, python installer was corrupted during download and the "/passive" argument passed at install time hides an error message
  - You didn't run the installer with administrator privileges (which is perfectly understandable) and you didn't validate an unlikely UAC for the python installer (Windows sometimes minimize it in the task bar, and you only have 2 minutes to validate it before it timeout) 

The Python 3.12 installation should not be a problem, as I can perfectly deploy biniou in a Windows environment already using Python 3.12.

I can only advise you to delete the existing biniou directory and relaunch the installer with administrator privileges.
You can also launch without admin rights, but you should then monitor the pre-requisites installation and watch for the UAC pop-ups. 

I close this issue as it really looks like a problem on your side, but don't hesitate to re-open it if required.

**Closed by Woolverine94** 2024-08-29 19:58 UTC
Labels: bug
